/**
 * Backend API client. Returns same shapes as youtube.ts.
 * Use when VITE_USE_BACKEND is set. Backend provides cache + DB + Piped.
 */

const API_BASE = '/api'

export interface VideoListItem {
  type?: 'video'
  title: string
  videoId: string
  author: string
  authorId: string
  authorUrl: string
  videoThumbnails: { quality: string; url: string; width: number; height: number }[]
  viewCount: number
  viewCountText?: string
  published: number
  publishedText: string
  lengthSeconds: number
  description?: string
  liveNow?: boolean
  authorThumbnails?: { url: string; width: number; height: number }[]
  authorVerified?: boolean
}

export interface VideoDetailDto extends VideoListItem {
  description: string
  descriptionHtml: string
  dashUrl?: string
  hlsUrl?: string
  adaptiveFormats: { url: string; qualityLabel?: string; type: string; container: string }[]
  formatStreams: { url: string; quality: string; qualityLabel: string }[]
  recommendedVideos: VideoListItem[]
  likeCount: number
  dislikeCount: number
  subscriberCount?: number
  subtitles?: { url: string; mimeType: string; name: string; code: string; autoGenerated: boolean }[]
}

export interface ChannelDto {
  id: string
  name: string
  avatarUrl: string
  bannerUrl: string
  description: string
  subscriberCount: number
  verified: boolean
  videos: VideoListItem[]
  nextpage: string | null
}

interface ApiResponse<T> {
  data: T
  meta?: { nextPage?: string; total?: number }
}

async function backendFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, init)
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error((err as { error?: string }).error ?? `Request failed: ${res.status}`)
  }
  const json = (await res.json()) as ApiResponse<T>
  return json.data
}

export async function getVideo(videoId: string): Promise<VideoDetailDto | null> {
  try {
    return await backendFetch<VideoDetailDto>(`/videos/${videoId}`)
  } catch {
    return null
  }
}

export async function getTrending(region = 'US'): Promise<VideoListItem[]> {
  try {
    return await backendFetch<VideoListItem[]>(`/trending?region=${encodeURIComponent(region)}`)
  } catch {
    return []
  }
}

export async function searchVideosPage(
  q: string,
  nextpage?: string,
  region?: string
): Promise<{ videos: VideoListItem[]; nextpage: string | null }> {
  const params = new URLSearchParams({ q, region: region ?? 'US' })
  if (nextpage) params.set('nextpage', nextpage)
  try {
    const res = await fetch(`${API_BASE}/search?${params}`)
    if (!res.ok) throw new Error('Search failed')
    const json = (await res.json()) as ApiResponse<VideoListItem[]> & { meta?: { nextPage?: string } }
    return {
      videos: json.data ?? [],
      nextpage: json.meta?.nextPage ?? null,
    }
  } catch {
    return { videos: [], nextpage: null }
  }
}

export async function getChannel(channelId: string): Promise<ChannelDto | null> {
  try {
    return await backendFetch<ChannelDto>(`/channels/${encodeURIComponent(channelId)}`)
  } catch {
    return null
  }
}

export async function recordView(videoId: string): Promise<void> {
  await fetch(`${API_BASE}/videos/${videoId}/view`, { method: 'POST' })
}
