import { useState, useEffect, useRef } from 'react'
import { File01, ChevronRight, Loading01 } from '@untitledui/icons'
import { cx } from '@/utils/cx'
import { fetchSubtitles, type SubtitleCue } from '@/utils/subtitles'
import type { SubtitleTrack } from '@/api/youtube'

export interface TranscriptPanelProps {
  subtitles: SubtitleTrack[]
  currentTime: number
  onSeek: (time: number) => void
  isOpen: boolean
  onToggle: () => void
}

function formatTimestamp(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

export function TranscriptPanel({
  subtitles,
  currentTime,
  onSeek,
  isOpen,
  onToggle,
}: TranscriptPanelProps) {
  const [cues, setCues] = useState<SubtitleCue[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [selectedTrack, setSelectedTrack] = useState<SubtitleTrack | null>(null)
  const listRef = useRef<HTMLDivElement>(null)
  const activeRef = useRef<HTMLButtonElement>(null)

  // Pick first track by default when subtitles change
  useEffect(() => {
    if (subtitles.length > 0 && !selectedTrack) {
      setSelectedTrack(subtitles[0])
    } else if (subtitles.length === 0) {
      setSelectedTrack(null)
      setCues([])
    }
  }, [subtitles, selectedTrack])

  // Fetch cues when track changes
  useEffect(() => {
    if (!selectedTrack?.url) {
      setCues([])
      return
    }
    setLoading(true)
    setError(null)
    fetchSubtitles(selectedTrack.url)
      .then(setCues)
      .catch((e) => {
        setError(e.message)
        setCues([])
      })
      .finally(() => setLoading(false))
  }, [selectedTrack?.url])

  // Scroll active cue into view
  useEffect(() => {
    if (!isOpen || !listRef.current || !activeRef.current) return
    activeRef.current.scrollIntoView({ block: 'nearest', behavior: 'smooth' })
  }, [currentTime, isOpen, cues])

  const activeIndex = cues.findIndex((c) => currentTime >= c.start && currentTime < c.end)

  if (subtitles.length === 0) return null

  return (
    <div className="flex flex-col">
      {/* Toggle button */}
      <button
        onClick={onToggle}
        className="flex w-full items-center justify-between gap-2 rounded-xl border border-gray-200 bg-white px-4 py-3 text-left transition-colors hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800/50 dark:hover:bg-gray-800"
        aria-expanded={isOpen}
      >
        <span className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-white">
          <File01 className="size-4 text-gray-500 dark:text-gray-400" />
          Transcript
        </span>
        <ChevronRight
          className={cx(
            'size-4 text-gray-400 transition-transform',
            isOpen && 'rotate-90'
          )}
        />
      </button>

      {isOpen && (
        <div className="mt-3 flex flex-col gap-3">
          {/* Language selector */}
          {subtitles.length > 1 && (
            <select
              value={selectedTrack?.code ?? ''}
              onChange={(e) => {
                const t = subtitles.find((s) => s.code === e.target.value)
                setSelectedTrack(t ?? null)
              }}
              className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-800"
            >
              {subtitles.map((s) => (
                <option key={s.code} value={s.code}>
                  {s.name} {s.autoGenerated ? '(auto)' : ''}
                </option>
              ))}
            </select>
          )}

          {/* Cue list */}
          <div
            ref={listRef}
            className="max-h-[min(60vh,400px)] overflow-y-auto rounded-xl border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-800/50"
          >
            {loading && (
              <div className="flex items-center justify-center gap-2 py-8 text-sm text-gray-500">
                <Loading01 className="size-4 animate-spin" />
                Loading transcript…
              </div>
            )}
            {error && (
              <div className="py-6 text-center text-sm text-red-500">
                {error}
              </div>
            )}
            {!loading && !error && cues.length === 0 && (
              <div className="py-6 text-center text-sm text-gray-500">
                No transcript available
              </div>
            )}
            {!loading && !error && cues.length > 0 && (
              <div className="divide-y divide-gray-100 dark:divide-gray-700">
                {cues.map((cue, i) => {
                  const isActive = i === activeIndex
                  return (
                    <button
                      key={`${cue.start}-${i}`}
                      ref={isActive ? activeRef : undefined}
                      onClick={() => onSeek(cue.start)}
                      className={cx(
                        'w-full px-4 py-3 text-left transition-colors',
                        isActive
                          ? 'bg-red-50 dark:bg-red-900/20'
                          : 'hover:bg-gray-50 dark:hover:bg-gray-800/50'
                      )}
                    >
                      <span className="text-xs font-medium tabular-nums text-gray-500 dark:text-gray-400">
                        {formatTimestamp(cue.start)}
                      </span>
                      <p
                        className={cx(
                          'mt-0.5 text-sm',
                          isActive
                            ? 'font-medium text-gray-900 dark:text-white'
                            : 'text-gray-700 dark:text-gray-300'
                        )}
                      >
                        {cue.text}
                      </p>
                    </button>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
